import { defineConfig, devices } from '@playwright/test'

/**
 * Playwright E2E configuration for LOOP_PROTOCOL.
 *
 * - Uses Vite preview server (started by webServer) — not the dev server.
 *   Run `pnpm test:e2e` for local (includes build), `pnpm test:e2e:ci` for CI (build done separately).
 * - VITE_E2E_MODE=true enables the read-only window.__LOOP_E2E__ observability hook.
 * - trace: 'retain-on-failure' ensures trace files are saved on any first failure
 *   (AC6: first-run failures are captured without requiring retries).
 *
 * Preview-namespace dedicated lane (Issue #1283 / PR #1517 review fix, P0
 * Blocker 1): `tests/e2e/m4-preview-namespace.spec.ts` asserts build-time
 * `VITE_LOOP_STORAGE_NAMESPACE` isolation against a production-like build
 * (no `VITE_E2E_MODE`). Running it in the same lane as the standard
 * `VITE_E2E_MODE=true`-only E2E suite let it silently pass via a fallback
 * that has since been removed from the spec itself — the spec now throws if
 * required env is missing instead. To prevent it from ever running against
 * the wrong build, it is EXCLUDED from the default test run here
 * (`testIgnore`) and is ONLY included when `LOOP_E2E_PREVIEW_NAMESPACE_LANE`
 * is `true` (`testMatch`), which also forces `reuseExistingServer: false` so
 * a stale server from a different worktree/build/PR cannot be reused. See
 * `pnpm run test:e2e:preview-namespace` in package.json.
 */

const PREVIEW_NAMESPACE_LANE = process.env.LOOP_E2E_PREVIEW_NAMESPACE_LANE === 'true'
const PREVIEW_NAMESPACE_SPEC = '**/m4-preview-namespace.spec.ts'

export default defineConfig({
  testDir: './tests/e2e',
  // Dedicated lane: ONLY the preview-namespace spec. Standard lane: every
  // other spec, with the preview-namespace spec excluded (never both).
  ...(PREVIEW_NAMESPACE_LANE
    ? { testMatch: [PREVIEW_NAMESPACE_SPEC] }
    : { testIgnore: [PREVIEW_NAMESPACE_SPEC] }),
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* One worker for consistent simulation timing */
  workers: 1,
  /* Reporter to use.
   * Preview-namespace lane writes its HTML report to a distinct output
   * folder (not the default `playwright-report/`) so its CI upload step
   * cannot collide with `scripts/check-visual-artifact-pipeline.py`'s fixed
   * id/name contract for the `playwright-report/` path (PR #1517 review
   * fix). */
  reporter: [
    ['html', { open: 'never', outputFolder: PREVIEW_NAMESPACE_LANE ? 'playwright-report-preview-namespace' : 'playwright-report' }],
    ['list'],
  ],
  use: {
    /* Base URL — matches the preview server port */
    baseURL: 'http://127.0.0.1:4173',
    /* Collect trace on failure (AC6) */
    trace: 'retain-on-failure',
    /* Screenshot on failure */
    screenshot: 'only-on-failure',
    /* Viewport matches default arena */
    viewport: { width: 1280, height: 720 },
  },

  /* Deterministic location for visual baselines generated by toHaveScreenshot(). */
  snapshotPathTemplate: '{testDir}/__screenshots__/{testFilePath}/{arg}{ext}',

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  /* Start the Vite preview server before running tests.
   * Uses preview (not dev) so the build is deterministic.
   * Standard lane: VITE_E2E_MODE=true enables the read-only __LOOP_E2E__ hook.
   * Preview-namespace lane: no VITE_E2E_MODE (production-like build/serve —
   * see file header); reuseExistingServer is always false so a stale server
   * from a different worktree/build/PR is never reused (P0 Blocker 1, item 5). */
  webServer: {
    command: PREVIEW_NAMESPACE_LANE
      ? 'pnpm exec vite preview --host 127.0.0.1 --port 4173 --strictPort'
      : 'VITE_E2E_MODE=true pnpm exec vite preview --host 127.0.0.1 --port 4173 --strictPort',
    url: 'http://127.0.0.1:4173',
    reuseExistingServer: PREVIEW_NAMESPACE_LANE ? false : !process.env.CI,
    timeout: 120_000,
    stdout: 'pipe',
    stderr: 'pipe',
  },
})
