#!/usr/bin/env python3
"""
plan_issue_scope_rollup.py

Read-only CLI that analyses a set of issues and PRs and produces an
ISSUE_SCOPE_ROLLUP_PLAN_V2 JSON payload describing merge / rollup candidates.

Usage:
    python3 plan_issue_scope_rollup.py --issues-json <path> --prs-json <path> [--current-issue <number>] [--repo <owner/repo>]

Mutation-free: this script never creates, edits, or closes any Issue or PR.

Exit codes:
    0 - success (completeness: full or partial with warnings)
    2 - current_issue not found in issues_json (completeness: partial, candidates: [])
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Schema constants
# ---------------------------------------------------------------------------

SCHEMA_VERSION = 2
SCHEMA_NAME = "ISSUE_SCOPE_ROLLUP_PLAN_V2"
SOURCE = "plan_issue_scope_rollup"

# Confidence levels
CONFIDENCE_HIGH = "high"
CONFIDENCE_MEDIUM = "medium"
CONFIDENCE_LOW = "low"

# Signals
SIGNAL_SHARED_DEDUPE_KEY = "shared_dedupe_key"
# Allowed-path signals (B3: split into three levels)
SIGNAL_EXACT_ALLOWED_PATH_OVERLAP = "exact_allowed_paths_equal"   # complete set equality
SIGNAL_ALLOWED_PATH_INTERSECTION = "allowed_path_intersection"    # non-empty intersection
SIGNAL_ALLOWED_PATH_PREFIX_OVERLAP = "allowed_path_prefix_overlap"  # prefix-level overlap
SIGNAL_SAME_PARENT_ISSUE = "same_parent_issue"
SIGNAL_SAME_SKILL_FAMILY = "same_skill_family"
SIGNAL_SAME_FAILURE_MODE_MARKER = "same_failure_mode_marker"

# Suggested actions
ACTION_MERGE_INTO_CURRENT_PR = "merge_into_current_pr"
ACTION_AMEND_CURRENT_ISSUE = "amend_current_issue"
ACTION_CREATE_PARENT_ROLLUP_ISSUE = "create_parent_rollup_issue"
ACTION_KEEP_SEPARATE_WITH_REASON = "keep_separate_with_reason"
ACTION_HUMAN_REVIEW_REQUIRED = "human_review_required"
ACTION_PROCEED_WITH_COORDINATION = "proceed_with_coordination"

# Regex for security-related keyword detection (word-boundary based).
# "auth" and "token" are intentionally excluded to avoid false positives on
# "author", "authored", "トークン消費", "token efficiency", etc.
SECURITY_RE = re.compile(
    r"\b("
    r"security|authentication|authorization|permission|sandbox|"
    r"privilege|secret|credential|oauth|api[_ -]?key"
    r")\b",
    re.IGNORECASE,
)

# Domain flag categories for audit purposes (not used for escalation decisions)
DOMAIN_SECURITY = "security"
DOMAIN_SCHEMA = "schema"
DOMAIN_METADATA = "metadata"
DOMAIN_WORKFLOW = "workflow"
DOMAIN_RUNTIME = "runtime"
DOMAIN_DOCS = "docs"

# Conflict types for scope_context
CONFLICT_SAME_ANCHOR_CONFLICTING_OP = "same_anchor_conflicting_operation"
CONFLICT_SAME_FILE_DISJOINT_ANCHOR = "same_file_disjoint_anchor"
CONFLICT_PREFIX_OVERLAP_UNCERTAIN = "prefix_overlap_uncertain"
CONFLICT_UNCERTAIN = "uncertain"
CONFLICT_NONE = "none"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _sha256_of_inputs(issues_raw: str, prs_raw: str) -> str:
    h = hashlib.sha256()
    h.update(issues_raw.encode("utf-8"))
    h.update(prs_raw.encode("utf-8"))
    return h.hexdigest()


def _compute_payload_sha256(plan_without_self_validation: dict[str, Any]) -> str:
    """Compute sha256 of canonical JSON bytes of plan (with self_validation excluded).

    Canonicalization: json.dumps with ensure_ascii=False, sort_keys=True,
    separators=(",", ":"), encoded as UTF-8. This is the project-local
    canonicalization method (RFC 8785 is intentionally not adopted).
    """
    canonical_bytes = json.dumps(
        plan_without_self_validation,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(canonical_bytes).hexdigest()


def _compute_script_file_sha256(script_path: Path) -> str:
    """Compute sha256 of raw file bytes (not Git blob hash)."""
    return hashlib.sha256(script_path.read_bytes()).hexdigest()


def _build_self_validation(
    plan_without_self_validation: dict[str, Any],
    invocation_id: str,
    script_path: Path,
) -> dict[str, Any]:
    """Build the self_validation block for ISSUE_SCOPE_ROLLUP_PLAN_V2.

    Fields:
    - invocation_id: UUID4 string (passed in; generated by caller if not provided)
    - payload_sha256: sha256 of canonical JSON bytes (self_validation excluded)
    - script_file_sha256: sha256 of raw script file bytes
    - schema_name: SCHEMA_NAME constant
    - schema_version: SCHEMA_VERSION constant
    - hash_algorithm: "sha256"
    - canonicalization: the project-local canonicalization method description
    """
    payload_sha256 = _compute_payload_sha256(plan_without_self_validation)
    script_file_sha256 = _compute_script_file_sha256(script_path)
    return {
        "invocation_id": invocation_id,
        "payload_sha256": payload_sha256,
        "script_file_sha256": script_file_sha256,
        "schema_name": SCHEMA_NAME,
        "schema_version": SCHEMA_VERSION,
        "hash_algorithm": "sha256",
        "canonicalization": (
            'json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")'
        ),
    }


def _load_json(path: str) -> tuple[list[dict[str, Any]], str]:
    """Return (parsed_list, raw_text).  Raises ValueError on parse error."""
    text = Path(path).read_text(encoding="utf-8")
    data = json.loads(text)
    if not isinstance(data, list):
        raise ValueError(f"Expected a JSON array in {path!r}, got {type(data).__name__}")
    return data, text


def _extract_field(item: dict[str, Any], *keys: str, default: Any = None) -> Any:
    for k in keys:
        if k in item:
            return item[k]
    return default


def _body_text(item: dict[str, Any]) -> str:
    return str(_extract_field(item, "body", default=""))


def _extract_dedupe_key(item: dict[str, Any]) -> str | None:
    """Extract dedupe_key from body (## Source section) or item field."""
    if "dedupe_key" in item:
        return str(item["dedupe_key"])
    body = _body_text(item)
    for line in body.splitlines():
        line = line.strip()
        if line.startswith("dedupe_key:"):
            val = line.split(":", 1)[1].strip().strip('"').strip("'")
            if val:
                return val
    return None


_CODE_SPAN_RE = re.compile(r"`([^`]+)`")


def _extract_path_from_bullet(line: str) -> str | None:
    """Extract a normalised path from a bullet line.

    Handles lines like:
      - `.claude/skills/foo.py`
      - `.claude/skills/foo.py`（新規作成）
      - .claude/skills/foo.py
    """
    # Prefer the first backtick-quoted span (strips annotations like （新規作成）)
    m = _CODE_SPAN_RE.search(line)
    if m:
        return m.group(1).strip().replace("\\", "/").rstrip("/") or None
    # Fall back to raw text after the bullet marker
    raw = line[2:].strip()
    # Take the first whitespace-separated token and strip stray backticks
    token = raw.split()[0].strip("`").replace("\\", "/").rstrip("/") if raw.split() else ""
    return token or None


def _extract_allowed_paths(item: dict[str, Any]) -> frozenset[str]:
    """Extract Allowed Paths list from the issue/PR body."""
    body = _body_text(item)
    paths: list[str] = []
    in_section = False
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("## Allowed Paths"):
            in_section = True
            continue
        if in_section:
            if stripped.startswith("## ") and not stripped.startswith("## Allowed Paths"):
                break
            if stripped.startswith("- ") or stripped.startswith("* "):
                path = _extract_path_from_bullet(stripped)
                if path:
                    paths.append(path)
    return frozenset(paths)


def _extract_parent_issue(item: dict[str, Any]) -> str | None:
    """Extract parent issue reference from body."""
    body = _body_text(item)
    for line in body.splitlines():
        stripped = line.strip().lower()
        if stripped.startswith("parent_issue:") or stripped.startswith("parent issue:"):
            val = line.split(":", 1)[1].strip().strip('"').strip("'")
            if val and val.lower() not in ("none", "null", ""):
                return val
    # check machine-readable contract block
    for line in body.splitlines():
        line_s = line.strip()
        if line_s.startswith("parent_issue:"):
            val = line_s.split(":", 1)[1].strip().strip('"').strip("'")
            if val and val.lower() not in ("none", "null", ""):
                return val
    return None


def _extract_skill_family(item: dict[str, Any]) -> str | None:
    """Derive a skill family from Allowed Paths or title keywords."""
    paths = _extract_allowed_paths(item)
    # Look for .claude/skills/<family>/ patterns
    families: set[str] = set()
    for p in paths:
        parts = p.replace("\\", "/").split("/")
        if ".claude" in parts and "skills" in parts:
            idx = parts.index("skills")
            if idx + 1 < len(parts):
                families.add(parts[idx + 1])
    if len(families) == 1:
        return next(iter(families))
    if len(families) > 1:
        # Multiple skill families in Allowed Paths -> return comma-joined (for signal purposes)
        return ",".join(sorted(families))
    # Fall back to title keywords
    title = str(_extract_field(item, "title", default=""))
    for keyword in ("issue-refinement-loop", "impl-review-loop", "review-issue", "create-issue", "edit-issue"):
        if keyword in title.lower():
            return keyword
    return None


def _extract_failure_mode_marker(item: dict[str, Any]) -> str | None:
    """Extract a failure mode marker from body (e.g. ## Failure Mode section)."""
    body = _body_text(item)
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("failure_mode_marker:") or stripped.startswith("failure_mode:"):
            val = stripped.split(":", 1)[1].strip().strip('"').strip("'")
            if val:
                return val
    return None


def _security_match_evidence(item: dict[str, Any]) -> list[str]:
    """Return list of matched security keywords (word-boundary based).

    "auth" and "token" are intentionally excluded — they cause false positives
    on "author", "authored", "トークン消費", "token efficiency" etc.
    """
    body = _body_text(item)
    title = str(_extract_field(item, "title", default=""))
    combined = title + " " + body
    return list({m.group(1).lower() for m in SECURITY_RE.finditer(combined)})


def _is_security_related(item: dict[str, Any]) -> bool:
    """Return True if the issue/PR touches security-sensitive areas."""
    return bool(_security_match_evidence(item))


def _classify_domain_flags(item: dict[str, Any]) -> list[str]:
    """Classify domain flags for audit purposes.

    Returns a list of domain categories that describe the change areas.
    These are audit-only and do NOT drive escalation decisions.
    Specifically, schema property names or metadata field names that contain
    security-adjacent words (e.g. "secret_policy") are classified as
    schema/metadata domains, NOT as security domain risks.
    """
    flags: list[str] = []
    body = _body_text(item)
    title = str(_extract_field(item, "title", default=""))
    combined = (title + " " + body).lower()
    allowed_paths = _extract_allowed_paths(item)
    paths_text = " ".join(allowed_paths).lower()

    # Security domain: triggered by real security keywords in context
    if _is_security_related(item):
        flags.append(DOMAIN_SECURITY)

    # Schema domain: JSON schema, YAML schema, data structure definitions
    schema_re = re.compile(
        r"\b(schema|json[_ -]?schema|yaml[_ -]?schema|data[_ -]?model|struct|type[_ -]?def)\b",
        re.IGNORECASE,
    )
    if schema_re.search(combined) or schema_re.search(paths_text):
        flags.append(DOMAIN_SCHEMA)

    # Metadata domain: configuration, policy files, field names, property names
    metadata_re = re.compile(
        r"\b(metadata|config|policy|settings|properties|fields|attributes|frontmatter)\b",
        re.IGNORECASE,
    )
    if metadata_re.search(combined) or metadata_re.search(paths_text):
        flags.append(DOMAIN_METADATA)

    # Workflow domain: CI/CD, orchestrator, loop, agent workflow
    workflow_re = re.compile(
        r"\b(workflow|orchestrat|loop|pipeline|ci[_/]?cd|github[_ -]?action)\b",
        re.IGNORECASE,
    )
    if workflow_re.search(combined) or workflow_re.search(paths_text):
        flags.append(DOMAIN_WORKFLOW)

    # Runtime domain: .claude/skills/, src/, tests/, scripts/
    runtime_path_prefixes = (".claude/skills", "src/", "tests/", "scripts/")
    if any(rp in paths_text for rp in runtime_path_prefixes):
        flags.append(DOMAIN_RUNTIME)

    # Docs domain: docs/ files
    if "docs/" in paths_text:
        flags.append(DOMAIN_DOCS)

    return sorted(set(flags))


# Regex for extracting sub-file anchors from issue/PR text.
# This is a lexical coordination detector, not an RFC 6901 strict parser.
# RFC 6901 strict parser ではない。The scan only finds JSON Pointer-like tokens.
# The negative lookbehind prevents matching slashes inside file paths or URLs
# (e.g. ".claude/skills/foo.py", "https://github.com/...") where the slash is
# preceded by a word character or backtick.
_JSON_POINTER_RE = re.compile(r"(?<![\w`])/[A-Za-z_][\w./-]*")
# Backtick-quoted anchors: property / field / symbol names (`phase_instance_id`,
# `secret_policy`) or backtick-wrapped JSON Pointers (`/required`,
# `/properties/foo/pattern`). The optional leading slash captures pointers that the
# bare _JSON_POINTER_RE skips because the preceding backtick is in its lookbehind set.
_BACKTICK_TOKEN_RE = re.compile(r"`(/?[A-Za-z_][\w./\-]*)`")


def _extract_anchor_tokens(item: dict[str, Any]) -> set[str]:
    """Extract sub-file anchor tokens from an issue/PR body.

    Anchors are structural positions *within* a file that a change targets:
    - JSON Pointers (RFC 6901 style): /required, /properties/foo/pattern
    - Backtick-quoted property / field / symbol names: `phase_instance_id`

    These let us distinguish "same file, different anchor" (disjoint, safe — e.g.
    #547 extends phase_instance_id while #549 adds /required to secret_policy) from
    "same file, same anchor" (conflicting operation, escalate).

    This extractor is a lexical coordination detector, not a semantic merge detector.
    RFC 6901 strict parser ではないし、coordination detector であり semantic merge
    detector ではない。It is intentionally a lightweight text scan. AST /
    tree-sitter anchoring is out of scope and tracked as a follow-up.
    """
    body = _body_text(item)
    title = str(_extract_field(item, "title", default=""))
    combined = title + "\n" + body
    tokens: set[str] = set()
    for m in _JSON_POINTER_RE.finditer(combined):
        tokens.add(m.group(0).rstrip("/.,):;").lower())
    for m in _BACKTICK_TOKEN_RE.finditer(combined):
        tok = m.group(1)
        # Skip backtick spans that are file paths (have an extension) — those are
        # anchor_paths, not sub-file anchors. (Paths starting with "." are already
        # excluded by the leading [A-Za-z_] requirement in the regex.)
        if re.search(r"\.[A-Za-z0-9]+$", tok):
            continue
        tokens.add(tok.lower())
    return tokens


def _build_scope_context(
    current: dict[str, Any],
    item: dict[str, Any],
    matched_paths: list[str],
    current_paths: frozenset[str],
    item_paths: frozenset[str],
    prefix_overlap_paths: list[str] | None = None,
) -> dict[str, Any]:
    """Build scope_context for a candidate pair.

    scope_context captures the structural relationship between the current issue
    and a candidate, including:
    - anchor_paths: overlapping file paths (structural positions; includes prefix
      "parent -> child" pairs when only a prefix overlap exists)
    - conflicting_anchors: shared sub-file anchors (JSON Pointers / property names)
    - domain_flags: semantic categories (audit-only, NOT used for escalation)
    - conflict_type: nature of the collision
    - escalation_required: true only for genuine structural conflicts

    Escalation policy (the core of #550):
    - Keyword-only / domain matches (e.g. a property name like "secret_policy", or a
      shared security keyword) do NOT constitute genuine conflicts. They are recorded
      in domain_flags / security_match_evidence for audit only.
      NOTE: scope rollup is NOT a security gate. Real-security-risk escalation
      (secret logging, Actions secrets, credential/permission/access-control) is the
      responsibility of a dedicated skill, not this generic collision detector.
    - same file + shared sub-file anchor -> same_anchor_conflicting_operation -> escalate
    - same file + disjoint sub-file anchors -> same_file_disjoint_anchor -> no escalate
      (this is the #547/#549 case)
    - exact same file set with NO machine-readable anchors to prove disjointness ->
      uncertain -> proceed_with_coordination (escalation_required=False; disjointness
      cannot be proven but this is not a genuine structural conflict)
    - partial path intersection without anchors -> same_file_disjoint_anchor -> no escalate
    - prefix-only overlap (no exact intersection) -> prefix_overlap_uncertain; the
      "parent -> child" pair is recorded in anchor_paths (never collapsed to "none").
      It escalates only on positive evidence (a shared sub-file anchor), consistent
      with #550's goal of reducing false escalation.

    Sub-file anchors are extracted with a lightweight text scan (JSON Pointer-like
    tokens and backtick-quoted names). This is NOT a strict RFC 6901 implementation
    (no ~0/~1 unescaping, no array-index semantics); precise AST / tree-sitter
    anchoring is out of scope and tracked as a follow-up.
    """
    domain_flags = _classify_domain_flags(item)
    current_anchors = _extract_anchor_tokens(current)
    item_anchors = _extract_anchor_tokens(item)
    shared_anchors = sorted(current_anchors & item_anchors)

    # No exact path intersection. Either a prefix-only overlap (record it, do not
    # collapse to "none" — #550 Blocker 4) or no path relationship at all.
    if not matched_paths:
        if prefix_overlap_paths:
            if current_anchors and item_anchors and shared_anchors:
                # Even across a prefix relationship, a shared anchor is positive
                # evidence of a conflicting operation.
                conflict_type = CONFLICT_SAME_ANCHOR_CONFLICTING_OP
                escalation_required = True
            else:
                conflict_type = CONFLICT_PREFIX_OVERLAP_UNCERTAIN
                escalation_required = False
            return {
                "anchor_paths": prefix_overlap_paths,
                "conflicting_anchors": shared_anchors,
                "domain_flags": domain_flags,
                "conflict_type": conflict_type,
                "escalation_required": escalation_required,
            }
        return {
            "anchor_paths": [],
            "conflicting_anchors": [],
            "domain_flags": domain_flags,
            "conflict_type": CONFLICT_NONE,
            "escalation_required": False,
        }

    exact_same_files = bool(current_paths) and bool(item_paths) and current_paths == item_paths

    if current_anchors and item_anchors:
        if shared_anchors:
            # Both target the same sub-file region — genuine conflicting operation.
            conflict_type = CONFLICT_SAME_ANCHOR_CONFLICTING_OP
            escalation_required = True
        else:
            # Same file(s), but disjoint sub-file anchors — independent changes.
            # This is the #547/#549 pattern that must NOT escalate.
            conflict_type = CONFLICT_SAME_FILE_DISJOINT_ANCHOR
            escalation_required = False
    elif exact_same_files:
        # Exact same file set but no machine-readable anchors to prove disjointness.
        # Disjointness cannot be proven, but this is not a genuine structural conflict
        # (no shared anchors). Proceed with coordination instead of blocking.
        conflict_type = CONFLICT_UNCERTAIN
        escalation_required = False
    else:
        # Partial path intersection without anchors — different file scopes overlap;
        # treat as disjoint to avoid false escalation.
        conflict_type = CONFLICT_SAME_FILE_DISJOINT_ANCHOR
        escalation_required = False

    return {
        "anchor_paths": matched_paths,
        "conflicting_anchors": shared_anchors,
        "domain_flags": domain_flags,
        "conflict_type": conflict_type,
        "escalation_required": escalation_required,
    }


def _determine_ordering_constraint(
    current: dict[str, Any],
    item: dict[str, Any],
    signals: list[str],
    confidence: str,
) -> str:
    """Determine ordering constraint between current issue and candidate.

    Returns one of:
    - "current_first": current issue should be merged/closed before candidate
    - "candidate_first": candidate should be merged/closed before current issue
    - "parallel_ok": both can proceed in parallel
    - "sequential_required": one must complete before the other (order TBD by human)

    This is a separate concern from suggested_action (what to do) and represents
    the temporal ordering recommendation.
    """
    if confidence == CONFIDENCE_HIGH:
        if SIGNAL_SHARED_DEDUPE_KEY in signals:
            return "parallel_ok"  # deduplication means they're the same change
        if SIGNAL_SAME_PARENT_ISSUE in signals:
            return "sequential_required"
        return "parallel_ok"

    if confidence == CONFIDENCE_MEDIUM:
        if SIGNAL_SAME_PARENT_ISSUE in signals:
            return "sequential_required"
        return "parallel_ok"

    return "parallel_ok"


def _determine_confidence(signals: list[str]) -> str:
    """
    Determine confidence level based on active signals.

    high conditions:
      - shared_dedupe_key
      - exact_allowed_paths_equal + same_parent_issue
      - exact_allowed_paths_equal + same_failure_mode_marker
      - allowed_path_intersection + same_parent_issue
      - allowed_path_intersection + same_failure_mode_marker
      NOTE: same_skill_family ONLY is NOT sufficient for high.

    medium:
      - exact_allowed_paths_equal (alone)
      - allowed_path_intersection (alone)
      - allowed_path_prefix_overlap + another signal
      - same_parent_issue (alone or with same_skill_family)
      - same_skill_family + another signal (except the combinations already at high)

    low:
      - same_skill_family only
      - allowed_path_prefix_overlap only
      - any single low-value signal
    """
    s = set(signals)

    if SIGNAL_SHARED_DEDUPE_KEY in s:
        return CONFIDENCE_HIGH

    # Treat exact equality or non-empty intersection as the path-overlap signal for high
    _has_path_overlap = (
        SIGNAL_EXACT_ALLOWED_PATH_OVERLAP in s or SIGNAL_ALLOWED_PATH_INTERSECTION in s
    )

    if _has_path_overlap and SIGNAL_SAME_PARENT_ISSUE in s:
        return CONFIDENCE_HIGH

    if _has_path_overlap and SIGNAL_SAME_FAILURE_MODE_MARKER in s:
        return CONFIDENCE_HIGH

    # same_skill_family ONLY -> must NOT be high (AC6 requirement)
    if s == {SIGNAL_SAME_SKILL_FAMILY}:
        return CONFIDENCE_LOW

    if _has_path_overlap:
        return CONFIDENCE_MEDIUM

    if SIGNAL_SAME_PARENT_ISSUE in s:
        return CONFIDENCE_MEDIUM

    if SIGNAL_SAME_SKILL_FAMILY in s and len(s) >= 2:
        return CONFIDENCE_MEDIUM

    if SIGNAL_SAME_FAILURE_MODE_MARKER in s:
        return CONFIDENCE_MEDIUM

    if SIGNAL_ALLOWED_PATH_PREFIX_OVERLAP in s and len(s) >= 2:
        return CONFIDENCE_MEDIUM

    return CONFIDENCE_LOW


def _suggested_action(
    item: dict[str, Any],
    signals: list[str],
    confidence: str,
    scope_context: dict[str, Any] | None = None,
) -> str:
    """Choose the appropriate suggested_action for a candidate.

    Escalation logic (revised from keyword-only to scope_context-based):
    - Previously: any security keyword match -> human_review_required
    - Now: escalation is driven by scope_context.escalation_required (genuine structural
      conflict — same_anchor_conflicting_operation with shared sub-file anchors).
      Security keywords alone (without structural conflict) are recorded in
      security_match_evidence for audit but do NOT trigger escalation.

    Evaluation order (CONFLICT_UNCERTAIN is checked BEFORE escalation_required):
    1. conflict_type == uncertain -> proceed_with_coordination
       uncertain = same file set, no machine-readable anchors to prove disjointness.
       This is NOT a genuine structural conflict; escalation_required is always False
       for CONFLICT_UNCERTAIN. However, the order is explicit so that a stale or
       erroneously-set escalation_required flag cannot override the CONFLICT_UNCERTAIN
       routing to proceed_with_coordination.
    2. escalation_required == True -> human_review_required
       Genuine structural conflict (same_anchor_conflicting_operation).

    Responsibility boundary:
    - CONFLICT_UNCERTAIN: "same file set, cannot prove disjointness" — proceed with
      coordination, NOT blocked. Coordination evidence is recorded in
      LOOP_STATE.scope_rollup_decision.related_coordination[].
    - same_anchor_conflicting_operation: both issues target the same sub-file anchor
      (JSON Pointer / property name) — genuine conflict, escalate.

    This prevents false positives where schema property names or metadata field names
    containing security-adjacent words (e.g. "secret_policy") cause spurious stops.
    The domain_flags field in scope_context serves as the audit trail for keyword matches.
    """
    # Use scope_context for escalation decisions if available.
    # CONFLICT_UNCERTAIN is evaluated FIRST to prevent a stale escalation_required flag
    # from overriding the proceed_with_coordination routing.
    if scope_context is not None:
        if scope_context.get("conflict_type") == CONFLICT_UNCERTAIN:
            # uncertain = same file set, no machine-readable anchors to prove disjointness.
            # This is NOT a genuine structural conflict (escalation_required=False).
            # Proceed with coordination rather than blocking.
            return ACTION_PROCEED_WITH_COORDINATION
        if scope_context.get("escalation_required", False):
            return ACTION_HUMAN_REVIEW_REQUIRED

    if confidence == CONFIDENCE_HIGH:
        if SIGNAL_SHARED_DEDUPE_KEY in signals:
            return ACTION_MERGE_INTO_CURRENT_PR
        _path_signals = {SIGNAL_EXACT_ALLOWED_PATH_OVERLAP, SIGNAL_ALLOWED_PATH_INTERSECTION}
        if any(s in signals for s in _path_signals) and SIGNAL_SAME_PARENT_ISSUE in signals:
            return ACTION_AMEND_CURRENT_ISSUE
        return ACTION_MERGE_INTO_CURRENT_PR

    if confidence == CONFIDENCE_MEDIUM:
        if SIGNAL_SAME_PARENT_ISSUE in signals:
            return ACTION_CREATE_PARENT_ROLLUP_ISSUE
        return ACTION_AMEND_CURRENT_ISSUE

    return ACTION_KEEP_SEPARATE_WITH_REASON


# ---------------------------------------------------------------------------
# Core analysis
# ---------------------------------------------------------------------------


def _extract_pr_file_paths(item: dict[str, Any]) -> frozenset[str]:
    """Extract file paths from a PR's `files` field (gh pr list --json files)."""
    files = item.get("files", [])
    if not isinstance(files, list):
        return frozenset()
    paths: list[str] = []
    for f in files:
        if isinstance(f, dict):
            path = f.get("path") or f.get("filename") or ""
        elif isinstance(f, str):
            path = f
        else:
            path = ""
        path = path.replace("\\", "/").rstrip("/")
        if path:
            paths.append(path)
    return frozenset(paths)


def _paths_share_prefix(a: frozenset[str], b: frozenset[str]) -> bool:
    """Return True if any path in *a* is a prefix of a path in *b* or vice versa."""
    for pa in a:
        for pb in b:
            short, long = (pa, pb) if len(pa) <= len(pb) else (pb, pa)
            if long.startswith(short.rstrip("/") + "/") or long == short:
                return True
    return False


def _prefix_overlap_pairs(a: frozenset[str], b: frozenset[str]) -> list[str]:
    """Return normalised "parent -> child" path pairs for prefix overlaps.

    Used so that prefix-overlap candidates record the structural relationship in
    scope_context.anchor_paths instead of leaving it empty (which previously caused
    conflict_type to collapse to "none" — see #550 Blocker 4).
    """
    pairs: list[str] = []
    for pa in a:
        for pb in b:
            short, long = (pa, pb) if len(pa) <= len(pb) else (pb, pa)
            if long != short and long.startswith(short.rstrip("/") + "/"):
                pairs.append(f"{short} -> {long}")
    return sorted(set(pairs))


def _non_mergeable_reasons(item: dict[str, Any], kind: str) -> list[str]:
    """Collect reasons why a candidate may not be directly mergeable."""
    reasons: list[str] = []
    state = str(item.get("state", "")).lower()
    state_reason = str(item.get("stateReason", "") or "").lower()
    if state == "closed":
        if state_reason == "not_planned":
            reasons.append("closed_not_planned")
        elif state_reason == "completed":
            reasons.append("closed_completed")
        else:
            reasons.append(f"closed({state_reason or 'unknown'})")
    return reasons


def _build_candidates(
    current: dict[str, Any] | None,
    items: list[dict[str, Any]],
    kind: str,
) -> list[dict[str, Any]]:
    """Build candidate entries for a list of items (issues or PRs)."""
    if current is None:
        return []

    current_number = _extract_field(current, "number", default=None)
    current_dedupe_key = _extract_dedupe_key(current)
    current_allowed_paths = _extract_allowed_paths(current)
    current_parent = _extract_parent_issue(current)
    current_skill_family = _extract_skill_family(current)
    current_failure_mode = _extract_failure_mode_marker(current)

    candidates: list[dict[str, Any]] = []

    for item in items:
        item_number = _extract_field(item, "number", default=None)
        if item_number == current_number and kind == "issue":
            continue  # skip the current issue itself

        signals: list[str] = []
        matched_paths: list[str] = []
        prefix_overlap_paths: list[str] = []

        # Signal: shared_dedupe_key
        item_dedupe_key = _extract_dedupe_key(item)
        if current_dedupe_key and item_dedupe_key and current_dedupe_key == item_dedupe_key:
            signals.append(SIGNAL_SHARED_DEDUPE_KEY)

        # Signal: allowed-path overlap (three levels — B3)
        # For PRs, use the `files` field as primary path signal
        if kind == "pr":
            item_allowed_paths = _extract_pr_file_paths(item) or _extract_allowed_paths(item)
        else:
            item_allowed_paths = _extract_allowed_paths(item)

        if current_allowed_paths and item_allowed_paths:
            overlap = current_allowed_paths & item_allowed_paths
            if overlap:
                matched_paths = sorted(overlap)
                if current_allowed_paths == item_allowed_paths:
                    signals.append(SIGNAL_EXACT_ALLOWED_PATH_OVERLAP)
                else:
                    signals.append(SIGNAL_ALLOWED_PATH_INTERSECTION)
            elif _paths_share_prefix(current_allowed_paths, item_allowed_paths):
                signals.append(SIGNAL_ALLOWED_PATH_PREFIX_OVERLAP)
                # Record the parent -> child relationship so scope_context does not
                # collapse to conflict_type: none (#550 Blocker 4).
                prefix_overlap_paths = _prefix_overlap_pairs(
                    current_allowed_paths, item_allowed_paths
                )

        # Signal: same_parent_issue
        item_parent = _extract_parent_issue(item)
        if (
            current_parent
            and item_parent
            and current_parent.strip() == item_parent.strip()
        ):
            signals.append(SIGNAL_SAME_PARENT_ISSUE)

        # Signal: same_skill_family
        item_skill_family = _extract_skill_family(item)
        if (
            current_skill_family
            and item_skill_family
            and current_skill_family == item_skill_family
        ):
            signals.append(SIGNAL_SAME_SKILL_FAMILY)

        # Signal: same_failure_mode_marker
        item_failure_mode = _extract_failure_mode_marker(item)
        if (
            current_failure_mode
            and item_failure_mode
            and current_failure_mode == item_failure_mode
        ):
            signals.append(SIGNAL_SAME_FAILURE_MODE_MARKER)

        if not signals:
            continue  # no relationship detected

        confidence = _determine_confidence(signals)

        # Build scope_context (structural position + domain classification + conflict type).
        # Pass the resolved Allowed Paths (item_allowed_paths uses PR `files` for PRs) so
        # scope_context anchors on the same path set used for signal detection.
        scope_context = _build_scope_context(
            current,
            item,
            matched_paths,
            current_allowed_paths,
            item_allowed_paths,
            prefix_overlap_paths,
        )

        action = _suggested_action(item, signals, confidence, scope_context)

        # ordering_constraint: separate from suggested_action (temporal ordering concern)
        ordering_constraint = _determine_ordering_constraint(current, item, signals, confidence)

        # dedupe_key for the candidate itself
        candidate_dedupe_key = item_dedupe_key or f"{kind}-{item_number}"

        # Security evidence (B4) — kept for audit/backward-compat, not used for escalation
        sec_evidence = _security_match_evidence(item)

        # Non-mergeable reasons (closed issues/PRs from --state all)
        nmr = _non_mergeable_reasons(item, kind)

        entry: dict[str, Any] = {
            "kind": kind,
            "number": item_number,
            "title": _extract_field(item, "title", default=None),
            "url": _extract_field(item, "url", default=None),
            "state": _extract_field(item, "state", default=None),
            "confidence": confidence,
            "dedupe_key": candidate_dedupe_key,
            "signals": signals,
            "matched_paths": matched_paths,
            "suggested_action": action,
            "scope_context": scope_context,
            "ordering_constraint": ordering_constraint,
        }
        if sec_evidence:
            entry["security_match_evidence"] = sec_evidence
        if nmr:
            entry["non_mergeable_reasons"] = nmr

        candidates.append(entry)

    return candidates


_CURRENT_ISSUE_NOT_FOUND = "current_issue_not_found"


def run(
    issues_json_path: str,
    prs_json_path: str,
    current_issue_number: int | None = None,
    repo: str = "",
    invocation_id: str | None = None,
    script_path: Path | None = None,
) -> tuple[dict[str, Any], int]:
    """Main analysis function.

    Returns (ISSUE_SCOPE_ROLLUP_PLAN_V2 dict, exit_code).

    exit_code == 2 when current_issue_number is specified but not found in
    issues_json (B1: fallback to first issue is prohibited).
    exit_code == 0 otherwise.

    invocation_id: UUID4 string for this invocation. If None, a new uuid4 is generated.
    script_path: Path to this script file (used for script_file_sha256). Defaults to
                 the actual script file location (__file__).
    """
    warnings: list[str] = []
    exit_code = 0

    # Resolve invocation_id (generate if not provided)
    if invocation_id is None:
        invocation_id = str(uuid.uuid4())

    # Resolve script_path (default to this file)
    if script_path is None:
        script_path = Path(__file__).resolve()

    try:
        issues, issues_raw = _load_json(issues_json_path)
    except (json.JSONDecodeError, ValueError) as exc:
        issues = []
        issues_raw = ""
        warnings.append(f"issues_json parse error: {exc}")

    try:
        prs, prs_raw = _load_json(prs_json_path)
    except (json.JSONDecodeError, ValueError) as exc:
        prs = []
        prs_raw = ""
        warnings.append(f"prs_json parse error: {exc}")

    body_sha256 = _sha256_of_inputs(issues_raw, prs_raw)

    # Identify the "current" issue — B1: NO fallback to first issue
    current_issue: dict[str, Any] | None = None
    if current_issue_number is not None:
        for iss in issues:
            if _extract_field(iss, "number", default=None) == current_issue_number:
                current_issue = iss
                break
        if current_issue is None:
            # B1: do NOT fall back to issues[0]; report partial completeness + exit 2
            warnings.append(_CURRENT_ISSUE_NOT_FOUND)
            exit_code = 2
    elif issues:
        current_issue = issues[0]

    completeness = "partial" if (warnings or exit_code != 0) else "full"

    if exit_code == 2:
        # B1: no candidates when current issue is not found
        all_candidates: list[dict[str, Any]] = []
    else:
        issue_candidates = _build_candidates(current_issue, issues, "issue")
        pr_candidates = _build_candidates(current_issue, prs, "pr")
        all_candidates = issue_candidates + pr_candidates

    plan_without_self_validation: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "repo": repo,
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "source": SOURCE,
        "body_sha256": body_sha256,
        "input": {
            "completeness": completeness,
            "warnings": warnings,
        },
        "candidates": all_candidates,
    }

    # Build self_validation block (payload_sha256 covers plan without self_validation)
    self_validation = _build_self_validation(
        plan_without_self_validation,
        invocation_id,
        script_path,
    )

    plan: dict[str, Any] = {**plan_without_self_validation, "self_validation": self_validation}

    return plan, exit_code


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Produce ISSUE_SCOPE_ROLLUP_PLAN_V2 JSON from issues and PRs lists."
    )
    parser.add_argument(
        "--issues-json",
        required=True,
        help="Path to JSON file containing a list of issues (gh issue list --json output).",
    )
    parser.add_argument(
        "--prs-json",
        required=True,
        help="Path to JSON file containing a list of PRs (gh pr list --json output).",
    )
    parser.add_argument(
        "--current-issue",
        type=int,
        default=None,
        help="Issue number of the current issue to compare against (optional).",
    )
    parser.add_argument(
        "--repo",
        default="",
        help="Repository in owner/repo format (informational only).",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output file path. Defaults to stdout.",
    )
    parser.add_argument(
        "--invocation-id",
        default=None,
        help=(
            "Invocation UUID for this run (optional). "
            "If not provided, a new uuid4 is generated automatically."
        ),
    )

    args = parser.parse_args(argv)

    plan, exit_code = run(
        issues_json_path=args.issues_json,
        prs_json_path=args.prs_json,
        current_issue_number=args.current_issue,
        repo=args.repo,
        invocation_id=args.invocation_id,
    )

    output_text = json.dumps(plan, ensure_ascii=False, indent=2)

    if args.output:
        Path(args.output).write_text(output_text, encoding="utf-8")
    else:
        print(output_text)

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
