"""scripts/claude-gpt/tests/test_spark_auth_deny_migration.py

Issue #2651: the Spark explicit-only authorization gate (Issue #2186) and
its nonce/session_id sidecar `spark-auth` directory have been retired from
`launch.sh` entirely -- there is no pending-authorization sidecar file left
to protect, so the `Write(<CLAUDE_GPT_HOME>/spark-auth/**)` /
`Edit(<CLAUDE_GPT_HOME>/spark-auth/**)` deny rules this file used to verify
(Issue #2440 AC1/AC2/AC3/AC6, the legacy-to-canonical migration of that
rule) no longer exist at all. Replaced (file path kept, per Issue #2651
Allowed Paths -- no file deletion) with a negative regression suite: no
`spark-auth` deny entry of any form is generated by `launch.sh --check-only`
any more, while the unrelated proxy config/state/home deny entries this
file also covered (Issue #2440 AC2) remain unaffected.

`_latitude_check_only_helper.py` の共有ハーネス（Issue #2426 由来、
`test_latitude_stop_hook_wiring.py` 等で既に使用）を再利用し、hermetic
`launch.sh --check-only` 起動ロジックを重複実装しない（DRY）。
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

_HELPER_PATH = Path(__file__).resolve().parent / "_latitude_check_only_helper.py"
_spec = importlib.util.spec_from_file_location(
    "claude_gpt_latitude_check_only_helper_2440_spark_auth_migration", _HELPER_PATH
)
_helper = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(_helper)

run_check_only = _helper.run_check_only


def _spark_auth_deny_entries(settings: dict) -> list[str]:
    deny = settings["permissions"]["deny"]
    return [rule for rule in deny if "spark-auth" in rule]


def test_no_spark_auth_deny_entry_of_any_form(tmp_path):
    """GIVEN 通常の launch.sh --check-only 実行（test-owned isolated
    CLAUDE_GPT_HOME）
    WHEN 生成された settings.local.json の permissions.deny を読む
    THEN spark-auth 向け deny エントリ（legacy Write(...) / canonical
    Edit(...) いずれの形も）は一切含まれない -- Spark 認可 gate と
    その sidecar ディレクトリ自体が撤去されたため（Issue #2651）。
    """
    result, settings_path = run_check_only(tmp_path)
    assert settings_path.exists(), result.stderr
    settings = json.loads(settings_path.read_text(encoding="utf-8"))

    entries = _spark_auth_deny_entries(settings)
    assert entries == [], entries


def test_unrelated_deny_entries_are_preserved(tmp_path):
    """GIVEN 通常の launch.sh --check-only 実行
    WHEN 生成された settings.local.json の permissions.deny を読む
    THEN proxy config/state/home dir 向けの既存 Read(...) deny エントリ群は
    削除・変更されず保持される（Issue #2440 AC2 の unrelated-preservation
    要件はそのまま維持）。
    """
    result, settings_path = run_check_only(tmp_path)
    assert settings_path.exists(), result.stderr
    settings = json.loads(settings_path.read_text(encoding="utf-8"))
    deny = settings["permissions"]["deny"]

    read_entries = [rule for rule in deny if rule.startswith("Read(")]
    # proxy config dir / proxy state dir / proxy home dir (spark-auth dir Read
    # is gone along with the retired gate -- Issue #2651).
    assert len(read_entries) == 3, read_entries
    assert not any("spark-auth" in rule for rule in read_entries), read_entries


def test_repeated_launch_never_reintroduces_spark_auth_deny(tmp_path):
    """GIVEN 同一 CLAUDE_GPT_HOME に対して launch.sh --check-only を連続2回
    実行する（既存の settings.local.json が存在する状態を含む）
    WHEN 2回目実行後の settings.local.json を読む
    THEN spark-auth deny エントリは依然として一切存在しない（毎回の完全
    再生成でも再出現しない）。
    """
    result1, settings_path = run_check_only(tmp_path)
    assert settings_path.exists(), result1.stderr
    assert settings_path.stat().st_size > 0

    result2, settings_path_second_run = run_check_only(tmp_path)
    assert settings_path_second_run == settings_path
    assert settings_path.exists(), result2.stderr

    settings = json.loads(settings_path.read_text(encoding="utf-8"))
    entries = _spark_auth_deny_entries(settings)
    assert entries == [], entries


def test_spark_auth_directory_is_not_created_under_isolated_home(tmp_path):
    """GIVEN test-owned isolated CLAUDE_GPT_HOME での launch.sh --check-only
    実行
    WHEN 実行後の CLAUDE_GPT_HOME 配下を確認する
    THEN `spark-auth` ディレクトリ自体が作成されない（Issue #2186 由来の
    sidecar auth directory 作成ロジックが撤去されたため）。
    """
    result, settings_path = run_check_only(tmp_path)
    assert settings_path.exists(), result.stderr
    # settings_path == <CLAUDE_GPT_HOME>/claude/settings.local.json
    claude_gpt_home = settings_path.parent.parent
    assert not (claude_gpt_home / "spark-auth").exists()
